# Generated by Django 6.0.7 on 2026-08-03 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_conditions', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('current_medications', models.JSONField(blank=True, default=list)),
                ('previous_surgeries', models.JSONField(blank=True, default=list)),
                ('smoking_status', models.CharField(choices=[('unknown', 'Unknown'), ('never', 'Never'), ('former', 'Former'), ('current', 'Current')], default='unknown', max_length=20)),
                ('alcohol_use', models.CharField(choices=[('unknown', 'Unknown'), ('never', 'Never'), ('former', 'Former'), ('current', 'Current')], default='unknown', max_length=20)),
                ('pregnancy_status', models.CharField(choices=[('not_applicable', 'Not applicable'), ('unknown', 'Unknown'), ('not_pregnant', 'Not pregnant'), ('pregnant', 'Pregnant')], default='not_applicable', max_length=20)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_health_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient health profile',
                'verbose_name_plural': 'Patient health profiles',
            },
        ),
    ]
