# Generated by Django 6.0.7 on 2026-08-04 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsession_user'),
        ('doctors', '0002_doctorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationClinicalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('structured_state', models.JSONField(default=dict)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('soon', 'Soon'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], db_index=True, max_length=20)),
                ('safety_decision', models.CharField(choices=[('continue', 'Continue'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], db_index=True, max_length=20)),
                ('execution_path', models.CharField(choices=[('backend_safety_response', 'Backend safety response'), ('ai_provider', 'AI provider')], max_length=40)),
                ('suggested_specialty_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_processed_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chatmessage')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_state', to='chat.chatsession')),
                ('suggested_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_clinical_states', to='doctors.specialty')),
            ],
            options={
                'verbose_name': 'Conversation clinical state',
                'verbose_name_plural': 'Conversation clinical states',
                'ordering': ['-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('schema_version__gte', 1)), name='clinical_schema_version_gte_1'), models.CheckConstraint(condition=models.Q(models.Q(('execution_path', 'backend_safety_response'), ('safety_decision', 'emergency'), ('urgency', 'emergency')), models.Q(('execution_path', 'ai_provider'), ('safety_decision__in', ['continue', 'urgent'])), _connector='OR'), name='clinical_execution_path_valid'), models.CheckConstraint(condition=models.Q(models.Q(('safety_decision', 'urgent'), _negated=True), ('urgency__in', ['urgent', 'emergency']), _connector='OR'), name='clinical_urgent_floor_valid')],
            },
        ),
    ]
