# Generated by Django 6.0.7 on 2026-08-01 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('medical_license_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('whatsapp_number', models.CharField(blank=True, max_length=32)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('working_hours', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('verification_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired')], db_index=True, default='inactive', max_length=20)),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'id'),
                'indexes': [models.Index(fields=['specialty', 'verification_status', 'subscription_status'], name='doctor_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subscription_started_at__isnull', True), ('subscription_expires_at__isnull', True), ('subscription_expires_at__gt', models.F('subscription_started_at')), _connector='OR'), name='doctor_subscription_dates_valid')],
            },
        ),
    ]
